#include <stdio.h>
#include <string.h>

// Function to check if the input string conforms to 'a*b+' rule
int isAccepted(char s[]) {
    int state = 0, i = 0;
    char c;

    // Loop through the characters in the input string
    while (s[i] != '\0') {
        switch (state) {
            case 0:
                c = s[i++];
                if (c == 'a')
                    state = 1;
                else if (c == 'b')
                    state = 2;
                else
                    state = 3;
                break;
            case 1:
                c = s[i++];
                if (c == 'a')
                    state = 1;
                else if (c == 'b')
                    state = 2;
                else
                    state = 3;
                break;
            case 2:
                c = s[i++];
                if (c == 'b')
                    state = 2;
                else
                    state = 3;
                break;
            default:
                return state; // If the string doesn't match the rule, return the current state
                break;
        }
    }

    return state; // Return the final state after processing the entire string
}

int main() {
    char s[20];
    char choice;

    printf("--Recognizing string generated by a*b+\n");

    do {
        printf("Enter string: ");
        gets(s); // Read a line of text (string) from the user

        int qn = isAccepted(s); // Call the function to check if the string is accepted
        if (qn == 2)
            printf("%s is accepted under rule 'a*b+'.\n", s);
        else
            printf("%s is not accepted under rule 'a*b+'.\n", s);

        // Ask if the user wants to continue
        printf("Do you want to continue? (y/n): ");
        scanf(" %c", &choice);
        getchar(); // Clear the newline character from the input buffer

    } while (choice == 'y' || choice == 'Y'); // Continue if the user enters 'y' or 'Y'

    printf("Program halted.\n"); // Print a message indicating program termination

    return 0;
}

